//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataExpressWeb.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:49558/wsCertTimbres.asmx")]
        public string DataExpressWeb_wsTimbres_wsCertTimbres {
            get {
                return ((string)(this["DataExpressWeb_wsTimbres_wsCertTimbres"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:49558/wsRecepcion.asmx")]
        public string DataExpressWeb_wsRecepcion_WsRecepcion {
            get {
                return ((string)(this["DataExpressWeb_wsRecepcion_WsRecepcion"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:49558/wsEmision.asmx")]
        public string DataExpressWeb_wsEmision_WsEmision {
            get {
                return ((string)(this["DataExpressWeb_wsEmision_WsEmision"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:49558/wsRestaurantes.asmx")]
        public string DataExpressWeb_wsRestaurantes_wsRestaurantes {
            get {
                return ((string)(this["DataExpressWeb_wsRestaurantes_wsRestaurantes"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:49558/wsMicros.asmx")]
        public string DataExpressWeb_wsMicros_wsMicros {
            get {
                return ((string)(this["DataExpressWeb_wsMicros_wsMicros"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.banxico.org.mx/DgieWSWeb/DgieWS")]
        public string DataExpressWeb_wsBanxico_DgieWS {
            get {
                return ((string)(this["DataExpressWeb_wsBanxico_DgieWS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:49558/wsHpresidente.asmx")]
        public string DataExpressWeb_wsHpresidente_wsHpresidente {
            get {
                return ((string)(this["DataExpressWeb_wsHpresidente_wsHpresidente"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:49558/wsDescargarZip.asmx")]
        public string DataExpressWeb_wsDescargarZip_wsDescargarZip {
            get {
                return ((string)(this["DataExpressWeb_wsDescargarZip_wsDescargarZip"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:49558/wsOpera.asmx")]
        public string DataExpressWeb_wsOpera_WsOpera {
            get {
                return ((string)(this["DataExpressWeb_wsOpera_WsOpera"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:49558/FacturaGlobalWeb.asmx")]
        public string DataExpressWeb_FacturaGlobalWeb_FacturaGlobalWeb {
            get {
                return ((string)(this["DataExpressWeb_FacturaGlobalWeb_FacturaGlobalWeb"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:49558/wsAloha.asmx")]
        public string DataExpressWeb_wsAloha_wsAloha {
            get {
                return ((string)(this["DataExpressWeb_wsAloha_wsAloha"]));
            }
        }
    }
}
